server:
  port: 8080

spring:
  application:
    name: s3-browser
  jackson:
    default-property-inclusion: non_null

# S3 Configuration (default MinIO settings)
s3:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin}
  bucket: ${S3_BUCKET:sampledata}
  region: ${S3_REGION:us-east-1}
  path-style-access: ${S3_PATH_STYLE_ACCESS:true}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Authentication Configuration
app:
  auth:
    username: ${APP_AUTH_USERNAME:admin}
    password: ${APP_AUTH_PASSWORD:admin}

# Logging
logging:
  level:
    com.enterprise.s3browser: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management/Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method